inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - rubocop-rspec
  - rubocop-thread_safety

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rails.yml
  - .rubocop/strict.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
