inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

inherit_gem:
  rubocop-fjord:
    - 'config/rubocop.yml'

inherit_from:
  - .rubocop/rails.yml
  - .rubocop/strict.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
