# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in national_government_organization_holiday.gemspec
gemspec

gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
