name: CD

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # See: https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # See: https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # See: https://caprover.com/docs/get-started.html#step-3-install-caprover-cli
      - run: npm install -g caprover
      # Future plans in the works to create tarball from within the caprover/deploy-from-github action.
      - uses: a7ul/tar-action@v1.1.3
        with:
          command: c
          cwd: "./.caprover"
          files: |
            captain-definition
            Dockerfile
          outPath: deploy.tar
      - uses: caprover/deploy-from-github@main
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.APP_NAME }}
          token: ${{ secrets.APP_TOKEN }}
